api_platform:
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 25
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header